export default{
	state:{
		categoryDialog:true,
		bookDialog:true,
		progressDialog:true,
		deleteCatDialog:true,
		msg:[],
		fadeOut:false
	},
	mutations:{
		hideDialog(state){
			state.categoryDialog=true;
			state.bookDialog=true;
			state.progressDialog=true;
			state.deleteCatDialog=true;
			state.fadeOut=false;
		},
		showCatDia(state){
			state.msg=[];
			state.categoryDialog=false;
		},
		showBoDia(state){
			state.msg=[];
			state.bookDialog=false;
		},
		showProDia(state){
			state.msg=[];
			state.progressDialog=false;
		},
		showdelCatDia(state){
			state.msg=[];
			state.deleteCatDialog=false;
		},
		addErrorInfo(state,msg){
			state.msg=msg;
		}
	},
	actions:{
		// 在hideDialog中将fadeout效果重置为false
		fadeOutDialog({commit,state}){
			state.fadeOut=true;
			setTimeout(function(){
				commit("hideDialog");
			},180);
		}
	}

}